sonar.projectKey=origenow_otimizacaoConsultaTTS
sonar.organization=origenow
sonar.projectName=otimizacaoConsultaTTS
sonar.projectVersion=1.0

sonar.sources=src,client/src
sonar.exclusions=node_modules/**,client/node_modules/**,client/dist/**,client/build/**,src/**/*.test.js,client/src/**/*.test.jsx,client/src/**/*.test.js,src/**/__tests__/**,client/src/**/__tests__/**
sonar.tests=src/__tests__,client/src/__tests__
sonar.test.inclusions=src/**/*.test.js,client/src/**/*.test.jsx,client/src/**/*.test.js

sonar.sourceEncoding=UTF-8
sonar.javascript.environments=node,browser
sonar.javascript.lcov.reportPaths=coverage/lcov.info,client/coverage/lcov.info
